baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "Rordorf Fonds | Rordorfscher Familienfonds | gegründet in Zürich 1710"

# URL Management
[permalinks]
  post = "/:year/:month/:title/"