backend:
  name: github
  repo: rordi/rordorf # Path to your Github repository
  branch: master # Branch to update (master by default)

display_url: https://www.rordorf.org
media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit

  - name: "page"
    label: "Seiten"
    folder: "site/content"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publikationsdatum", name: "date", widget: "datetime"}
      - {label: "Seiteninhalt", name: "body", widget: "markdown"}

  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Blogbeiträge" # Used in the UI, e.g., "New Post"
    folder: "site/content/posts" # The path to the folder where the documents are stored
    slug: "{{year}}-{{slug}}" # generated filename
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Titel"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Publikationsdatum"
        name: "date"
        widget: "datetime"
      - label: "Autoren"
        name: "authors"
        widget: "list"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Bild"
        name: "image"
        widget: "image"
      - label: "Beitrag"
        name: "body"
        widget: "markdown"

  - name: "event"
    label: "Kalendereinträge"
    folder: "site/content/event"
    slug: "{{year}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Titel"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Publikationsdatum"
        name: "date"
        widget: "datetime"
      - label: "Event Startdatum"
        name: "eventDate"
        widget: "datetime"
      - label: "Event Startzeit"
        name: "eventTime"
        widget: "string"
      - label: "Event Ort"
        name: "location"
        widget: "string"
      - label: "Autoren"
        name: "authors"
        widget: "list"
      - label: "Bild"
        name: "image"
        widget: "image"
      - label: "Beschreibung"
        name: "body"
        widget: "markdown"
